<?php

/**
 * @file
 * UTexas Pantheon Logs HTTP module.
 */

use GuzzleHttp\Exception\RequestException;

/**
 * Runs on shutdown to clean up and display developer information.
 *
 * @see \Drupal\utexas_pantheon_logs_http\EventSubscriber\LogsHttpEventSubscriber
 */
function utexas_pantheon_logs_http_shutdown() {
  /** @var \Drupal\utexas_pantheon_logs_http\Logger\UtexasPantheonLogsHttpLogger $logs_http_logger */
  $logs_http_logger = \Drupal::service('utexas_pantheon_logs_http.utexas_pantheon_logs_http_logger');
  if (!$logs_http_logger->isEnabled()) {
    return;
  }

  if (!$events = $logs_http_logger->getEvents()) {
    return;
  }

  $url = $logs_http_logger->getUrl();
  $url = [
    sprintf("%s:443:127.0.0.1:%d",
    $url,
    $logs_http_logger->getPantheonStunnel()),
  ];
  \Drupal::logger('utexas_pantheon_logs_http')->notice(implode(',', $url));
  // \Drupal::logger('utexas_pantheon_logs_http')->notice($logs_http_logger->getPantheonStunnel());
  // Send events to logs.
  foreach ($events as $event) {
    $client = \Drupal::httpClient();

    try {
      // Send data to Logs.
      $client->post($url, [
        'json' => $event,
        'headers' => $logs_http_logger->getHttpHeaders(),
      ]);
    }
    catch (RequestException $e) {

    }
  }
}
